Usability and config updates.

diff --git a/camera-rtmp b/camera-rtmp
--- a/camera-rtmp
+++ b/camera-rtmp
@@ -1,17 +1,30 @@
 #!/usr/bin/env bash
 
-CAMERA_IP=""
-CAMERA_PORT="88" # "88" is a common default
-CAMERA_USERNAME="admin"
-CAMERA_PASSWORD="password123"
-CAMERA_STREAMNAME="videoMain" # "videoMain" or "videoSub"
+source_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)";
+cd "${source_dir}";
 
-SERVER_STREAM_KEY=""
+COLOUR_GREEN='\033[0;32m'
+COLOUR_YELLOW='\033[0;33m'
+COLOUR_PURPLE='\033[0;35m'
+COLOUR_RED='\033[0;31m'
+DECOR_BOLD='\033[1m';
+COLOUR_DECOR_OFF='\033[0;00m'
+CLEAR_LINE='\033[2K'
 
-while [ 1 ]
+if [ ! -f "camera-credentials" ];
+then
+    echo -e "${COLOUR_RED}${DECOR_BOLD}Error${COLOUR_DECOR_OFF}: Configuration file '${DECOR_BOLD}camera-credentials${COLOUR_DECOR_OFF}' not found.";
+    echo " - Copy 'camera-credentials.template' to 'camera-credentials'";
+    echo " - Edit 'camera-credentials' for your camera & stream login details.";
+    exit 1;
+fi
+
+source camera-credentials;
+
+while [ 1 ];
 do
   echo "SWHR camera-rtmp: Starting ffmpeg.."
-  ffmpeg -hide_banner -rtsp_transport tcp -i rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_IP}:${CAMERA_PORT}/${CAMERA_STREAMNAME} -c:v copy -an -f flv rtmp://swhr.org.uk:1935/live/${SERVER_STREAM_KEY};
-  echo "SWHR camera-rtmp: WARNING ffmpeg exited, waiting 1 second.."
+  ffmpeg -hide_banner -nostats -loglevel warning -rtsp_transport tcp -i rtsp://${CAMERA_USERNAME}:${CAMERA_PASSWORD}@${CAMERA_IP_ADDRESS}:${CAMERA_PORT}/${CAMERA_STREAMNAME} -c:v copy -an -f flv rtmp://swhr.org.uk:1935/live/${RTMP_STREAM_KEY};
+  echo -e "SWHR camera-rtmp: ${COLOUR_RED}${DECOR_BOLD}WARNING${COLOUR_DECOR_OFF} ffmpeg exited, waiting 1 second.."
   sleep 1;
 done
diff --git a/rtmp-watchdog b/rtmp-watchdog
--- a/rtmp-watchdog
+++ b/rtmp-watchdog
@@ -3,31 +3,50 @@
 # Note 1: This server will kill all ffmpeg processes, so doesn't coexist with other applications well!
 # Note 2: This script requires passwordless sudo
 
-SERVER_STREAM_NAME="out1"
+source_dir="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd)";
+cd "${source_dir}";
+
+COLOUR_GREEN='\033[0;32m'
+COLOUR_YELLOW='\033[0;33m'
+COLOUR_PURPLE='\033[0;35m'
+COLOUR_RED='\033[0;31m'
+DECOR_BOLD='\033[1m';
+COLOUR_DECOR_OFF='\033[0;00m'
+CLEAR_LINE='\033[2K'
+
+if [ ! -f "camera-credentials" ];
+then
+    echo -e "${COLOUR_RED}${DECOR_BOLD}Error${COLOUR_DECOR_OFF}: Configuration file '${DECOR_BOLD}camera-credentials${COLOUR_DECOR_OFF}' not found.";
+    echo " - Copy 'camera-credentials.template' to 'camera-credentials'";
+    echo " - Edit 'camera-credentials' for your camera & stream login details.";
+    exit 1;
+fi
+
+source camera-credentials;
 
 fail=10
-while [ 1 ]
+while [ 1 ];
 do
-  echo "SWHR rtmp-watchdog: querying server.."
-  if curl -s 'https://swhr.org.uk/rtmp/status' | grep "${SERVER_STREAM_NAME}" >/dev/null
+  echo "SWHR rtmp-watchdog: querying server..";
+  if curl -s 'https://swhr.org.uk/rtmp/status' | grep "<name>${RTMP_STREAM_NAME}</name>" >/dev/null;
   then
-    # We got a response and the SERVER_STREAM_NAME was in it, so all ok, reset counter
-    echo "SWHR rtmp-watchdog: stream ok"
+    # We got a response and the RTMP_STREAM_NAME was in it, so all ok, reset counter
+    echo "SWHR rtmp-watchdog: stream ok";
     fail=10
   else
     # Either there was no response, so internet is down and maybe a good idea to restart ffmpeg anyway,
     #  or we got a response, but the stream isn't running, so we might need to restart ffmpeg
     #  so, decrement the counter
     fail=$((fail-1))
-    echo "SWHR rtmp-watchdog: WARNING stream fail! ${fail} attempts remaining"
+    echo "SWHR rtmp-watchdog: WARNING stream fail! ${fail} attempts remaining";
     # The counter will be less than 1 if we've had 10 consecutive failures (approx 12 seconds or a bit more)
-    if [[ "${fail}" -lt 1 ]]
+    if [[ "${fail}" -lt 1 ]];
     then
       # Counter is 0, so reset ffmpeg, then give it a bit longer (~25 seconds) for the stream to come back
-      echo "SWHR rtmp-watchdog: Killing ffmpeg so it restarts!"
-      sudo killall -9 ffmpeg
+      echo "SWHR rtmp-watchdog: Killing ffmpeg so it restarts!";
+      sudo killall -9 ffmpeg;
       fail=20
     fi
   fi
-  sleep 1
+  sleep 1;
 done
